-- ============================================================
-- RUDDHAA ERP — ACCOUNTING CORE SCHEMA (Phase 1)
-- Built fresh. Does not depend on, or reuse, any prior schema.
-- ============================================================

-- ------------------------------------------------------------
-- CHART OF ACCOUNTS
-- Single source of truth for every account. Never deleted,
-- only deactivated (is_active = false).
-- ------------------------------------------------------------
create table chart_of_accounts (
  id              bigserial primary key,
  account_code    text        not null unique,
  account_name    text        not null,
  account_type    text        not null check (account_type in ('asset','liability','equity','income','expense')),
  parent_id       bigint      references chart_of_accounts(id),
  is_system       boolean     not null default false,   -- system accounts cannot be deleted/renamed via API
  is_active       boolean     not null default true,
  opening_balance numeric(18,2) not null default 0,
  opening_type    text        not null default 'debit' check (opening_type in ('debit','credit')),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index idx_coa_type   on chart_of_accounts(account_type);
create index idx_coa_active on chart_of_accounts(is_active);

-- Needed for the exclusion constraint below (overlap detection on
-- date ranges using a plain btree-indexable type).
create extension if not exists btree_gist;

-- ------------------------------------------------------------
-- FINANCIAL YEARS
-- Only an 'open' financial year accepts postings.
-- ------------------------------------------------------------
create table financial_years (
  id          bigserial primary key,
  code        text        not null unique,       -- e.g. '2026-27'
  start_date  date        not null,
  end_date    date        not null,
  status      text        not null default 'open' check (status in ('open','closed','archived')),
  created_at  timestamptz not null default now(),
  check (end_date > start_date),
  -- Two financial years can never cover overlapping dates — without
  -- this, requireOpenFinancialYear() (lib/fy.ts) could match more
  -- than one row for the same posting date with no defined tie-break,
  -- silently posting against whichever one Postgres happened to
  -- return first.
  exclude using gist (daterange(start_date, end_date, '[]') with &&)
);

-- ------------------------------------------------------------
-- NUMBERING SEQUENCES
-- One row per (document_type, financial_year). The engine
-- increments this atomically under a row lock — see
-- lib/number-generator.ts. Never generated by the frontend.
-- ------------------------------------------------------------
create table numbering_sequences (
  id                bigserial primary key,
  document_type     text        not null,          -- 'journal_entry' | 'invoice' | 'receipt' | 'payment' | ...
  financial_year_id bigint      not null references financial_years(id),
  prefix            text        not null default '',
  next_number       integer     not null default 1,
  padding           integer     not null default 4,
  unique (document_type, financial_year_id)
);

-- ------------------------------------------------------------
-- JOURNAL ENTRIES (the ledger's only source)
-- Lifecycle: draft -> posted -> cancelled (reversed)
-- Posted entries are immutable at the application layer;
-- corrections only ever happen via a reversing entry.
-- ------------------------------------------------------------
create table journal_entries (
  id                  bigserial primary key,
  je_no               text        not null unique,
  financial_year_id   bigint      not null references financial_years(id),
  entry_date          date        not null,
  narration           text        not null,
  source_type         text        not null,        -- 'manual' | 'invoice' | 'purchase' | 'receipt' | 'payment' | 'reversal'
  source_id           bigint,                       -- id of the originating document, if any
  status              text        not null default 'draft' check (status in ('draft','posted','cancelled')),
  reversed_by_je_id    bigint      references journal_entries(id),  -- set on the ORIGINAL entry once reversed
  reverses_je_id       bigint      references journal_entries(id),  -- set on the REVERSING entry
  posted_at           timestamptz,
  posted_by           bigint,
  created_at          timestamptz not null default now()
);

create index idx_je_date   on journal_entries(entry_date);
create index idx_je_status on journal_entries(status);
create index idx_je_source on journal_entries(source_type, source_id);

-- ------------------------------------------------------------
-- JOURNAL ENTRY LINES
-- Minimum two lines per entry; debit total = credit total,
-- enforced by the posting engine before any row is written.
-- ------------------------------------------------------------
create table journal_entry_lines (
  id                bigserial primary key,
  journal_entry_id  bigint      not null references journal_entries(id) on delete restrict,
  account_id        bigint      not null references chart_of_accounts(id),
  debit             numeric(18,2) not null default 0,
  credit            numeric(18,2) not null default 0,
  narration         text,
  party_type        text,                            -- 'customer' | 'vendor' | null
  party_id          bigint,
  line_no           integer     not null,
  check (debit >= 0 and credit >= 0),
  check (not (debit > 0 and credit > 0)),             -- a line is either a debit or a credit, never both
  unique (journal_entry_id, line_no)
);

create index idx_jel_je      on journal_entry_lines(journal_entry_id);
create index idx_jel_account on journal_entry_lines(account_id);
create index idx_jel_party   on journal_entry_lines(party_type, party_id);

-- ------------------------------------------------------------
-- AUDIT LOG
-- Append-only. Never editable, never deleted.
-- ------------------------------------------------------------
create table audit_log (
  id           bigserial primary key,
  user_id      bigint,
  action       text        not null,   -- 'create' | 'post' | 'cancel' | 'reverse' | 'update' | 'deactivate'
  module       text        not null,   -- 'journal_entry' | 'chart_of_accounts' | ...
  record_id    bigint,
  old_value    jsonb,
  new_value    jsonb,
  ip_address   text,
  performed_at timestamptz not null default now()
);

create index idx_audit_module on audit_log(module, record_id);
create index idx_audit_time   on audit_log(performed_at);

-- ------------------------------------------------------------
-- EMPLOYEES (authentication)
-- Minimal, real auth so postings have a genuine userId for the
-- audit trail. Full role/permission matrix is a Phase 4 concern —
-- this table exists now only so nothing in Phase 1 has to fake
-- "userId: 1" to work.
-- ------------------------------------------------------------
create table employees (
  id            bigserial primary key,
  username      text        not null unique,
  email         text unique,
  password_hash text        not null,
  employee_name text        not null,
  is_active     boolean     not null default true,
  created_at    timestamptz not null default now()
);

-- ------------------------------------------------------------
-- SEED: minimal, unambiguous system accounts.
-- Real chart-of-accounts design is a Phase 2/3 concern once
-- customers/vendors/invoices exist — this seed only exists so
-- the posting engine has something valid to post against
-- during Phase 1 testing.
-- ------------------------------------------------------------
insert into chart_of_accounts (account_code, account_name, account_type, is_system) values
  ('1000', 'Cash',              'asset',     true),
  ('1100', 'Bank',              'asset',     true),
  ('1200', 'Trade Debtors',     'asset',     true),
  ('2100', 'Trade Creditors',   'liability', true),
  ('3000', 'Capital',           'equity',    true),
  ('4000', 'Sales',             'income',    true),
  ('5000', 'Purchases',         'expense',   true),
  ('5900', 'Miscellaneous Expense', 'expense', true);
