#!/usr/bin/env bash
# Permission enforcement: verify fail-closed behavior.
# Tests both authorized (200) and unauthorized (401/403) access for
# a fresh employee who has no permissions beyond the EMPLOYEE baseline.
set -euo pipefail
BASE="${BASE_URL:-http://localhost:3000}"
USER="${SEED_USERNAME:-admin}"
PASS="${SEED_PASSWORD:?Set SEED_PASSWORD}"

echo "== Login as SYSTEM_ADMIN =="
ADMIN_TOKEN=$(curl -sf -X POST "$BASE/api/auth/login" -H "content-type: application/json" \
  -d "{\"username\":\"$USER\",\"password\":\"$PASS\"}" | python3 -c 'import sys,json;print(json.load(sys.stdin)["token"])')
ADMIN_AUTH=(-H "authorization: Bearer $ADMIN_TOKEN")

echo "== SYSTEM_ADMIN: access hr/employees (expect 200) =="
STATUS=$(curl -so /dev/null -w "%{http_code}" "${ADMIN_AUTH[@]}" "$BASE/api/hr/employees")
[ "$STATUS" = "200" ] && echo "PASS 200" || echo "FAIL expected 200, got $STATUS"

echo "== No token: access hr/employees (expect 401) =="
STATUS=$(curl -so /dev/null -w "%{http_code}" "$BASE/api/hr/employees")
[ "$STATUS" = "401" ] && echo "PASS 401" || echo "FAIL expected 401, got $STATUS"

echo "== Create a test employee to use as an unprivileged user =="
CODE="PERM-TEST-$(date +%s)"
CREATE=$(curl -sf -X POST "${ADMIN_AUTH[@]}" -H "content-type: application/json" "$BASE/api/hr/employees" -d "{
  \"employeeCode\": \"$CODE\", \"employeeName\": \"Permission Test User\",
  \"joiningDate\": \"$(date +%Y-%m-%d)\"
}")
EMP_ID=$(echo "$CREATE" | python3 -c 'import sys,json;r=json.load(sys.stdin);print(r.get("employee_id",""))')
echo "Created employee $EMP_ID"

echo "== Get that employee's login username (= lowercase of employee code) =="
UNPRIVILEGED_USER=$(echo "$CODE" | tr '[:upper:]' '[:lower:]')
echo "Username: $UNPRIVILEGED_USER"
echo "(Temp password was generated by createEmployee — reset it to test login)"
echo "  psql \"\$DATABASE_URL\" -c \"update employees set password_hash = '<bcrypt-of-known-password>' where username = '$UNPRIVILEGED_USER';\""
echo ""
echo "If you've done that, set UNPRIVILEGED_PASS and uncomment the block below."

# Uncomment once you've set the temp password manually:
# UNPRIVILEGED_PASS="<known-password>"
# UNPRIVILEGED_TOKEN=$(curl -sf -X POST "$BASE/api/auth/login" -H "content-type: application/json" \
#   -d "{\"username\":\"$UNPRIVILEGED_USER\",\"password\":\"$UNPRIVILEGED_PASS\"}" | python3 -c 'import sys,json;print(json.load(sys.stdin)["token"])')
# UNPRIV_AUTH=(-H "authorization: Bearer $UNPRIVILEGED_TOKEN")
# 
# echo "== Unprivileged: GET /api/hr/employees (expect 403 — needs hr.employee.view) =="
# STATUS=$(curl -so /dev/null -w "%{http_code}" "${UNPRIV_AUTH[@]}" "$BASE/api/hr/employees")
# [ "$STATUS" = "403" ] && echo "PASS 403" || echo "FAIL expected 403, got $STATUS"
# 
# echo "== Unprivileged: own leave self-service endpoint (expect 200 — EMPLOYEE role has leave.apply) =="
# STATUS=$(curl -so /dev/null -w "%{http_code}" "${UNPRIV_AUTH[@]}" "$BASE/api/leave/requests/my")
# [ "$STATUS" = "200" ] && echo "PASS 200" || echo "FAIL expected 200, got $STATUS"
# 
# echo "== Unprivileged: payroll post (expect 403 — needs payroll.post) =="
# STATUS=$(curl -so /dev/null -w "%{http_code}" -X POST "${UNPRIV_AUTH[@]}" "$BASE/api/payroll/posting/1/post")
# [ "$STATUS" = "403" ] && echo "PASS 403" || echo "FAIL expected 403, got $STATUS"

echo ""
echo "== Structured permission check via API (SYSTEM_ADMIN sees all permission codes) =="
curl -sf "${ADMIN_AUTH[@]}" "$BASE/api/permissions" | python3 -c \
  'import sys,json;d=json.load(sys.stdin);print(f"{len(d)} permission codes registered");[print(" ", p["permission_code"]) for p in sorted(d, key=lambda x:x["permission_code"])]'
